# Generated by Django 4.1.2 on 2023-03-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Имя покупателя')),
                ('email', models.EmailField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Почта покупателя')),
                ('phone', models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Номер покупателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Определяется автоматически, возможно редактирование', verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если товар должен быть удалена')),
                ('order', models.ManyToManyField(to='orders.order')),
            ],
        ),
    ]
