# Generated by Django 4.1.2 on 2022-12-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='orders.order')),
            ],
        ),
    ]
