# Generated by Django 4.1.2 on 2023-01-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendAutomaticly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Формат: обязательный', max_length=254, verbose_name='Почта для отправки смс покупателю')),
                ('subject', models.CharField(help_text='Формат: обязательный', max_length=255, verbose_name='Шапка смс для отправки почты покупателю')),
                ('text', models.TextField(help_text='Формат: обязательный', verbose_name='Текст смс для отправки почты покупателю')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Нажать, если нужно удалить шаблон')),
            ],
        ),
        migrations.CreateModel(
            name='EmailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Формат: обязательный', max_length=255, verbose_name='Почта клиента, оформившего и купившего товары (заказ)')),
                ('message', models.TextField(help_text='Формат: обязательный', verbose_name='Текст сообщения')),
                ('order', models.ForeignKey(blank=True, help_text='Формат: обязательный', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='orders.order', verbose_name='Текущий заказ клиента')),
            ],
        ),
    ]
