# Generated by Django 4.1.2 on 2022-12-11 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='orders.order'),
        ),
    ]
