# Generated by Django 4.1.2 on 2023-03-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Формат: обязательный', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='orders.order', verbose_name='Текущий заказ клиента'),
        ),
    ]
