# Generated by Django 4.1.2 on 2023-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailentry',
            name='message',
        ),
        migrations.AddField(
            model_name='emailentry',
            name='from_email',
            field=models.EmailField(default='', help_text='Required, type an email address', max_length=200, verbose_name='Current sender'),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='subject',
            field=models.CharField(default='asasas', help_text='Required, type something', max_length=255, verbose_name='Email header subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailentry',
            name='template_name',
            field=models.CharField(blank=True, help_text='Required if needed, type file name', max_length=255, null=True, verbose_name='Email template'),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='text',
            field=models.TextField(blank=True, help_text='Required if needed, type some text', null=True, verbose_name='Email text input'),
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='email',
            field=models.EmailField(help_text='Required, type an email address', max_length=200, verbose_name='Mail recipient'),
        ),
    ]
