# Generated by Django 4.1.2 on 2023-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_emailsendautomaticly_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательный, принимает текст', max_length=255, verbose_name='Имя шаблона')),
                ('html_template', models.TextField(help_text='Обязательный, принимает html code', verbose_name='HTML код сообщения')),
            ],
        ),
        migrations.AddField(
            model_name='emailsendautomaticly',
            name='deliered',
            field=models.BooleanField(default=False, verbose_name='Галочка стоит, если имейл доставлен'),
        ),
    ]
