# Generated by Django 4.1.2 on 2023-03-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_emailsendtemplate_emailsendautomaticly_deliered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsendtemplate',
            options={'verbose_name': 'Шаблоны кастомных имейлов'},
        ),
        migrations.AlterField(
            model_name='emailsendautomaticly',
            name='template_name',
            field=models.ForeignKey(blank=True, help_text='Название шаблона', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_emails', to='mailing.emailsendtemplate', verbose_name='Имя шаблона письма'),
        ),
    ]
