# Generated by Django 4.1.2 on 2023-03-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_emailsendtemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsendautomaticly',
            old_name='template_name',
            new_name='template',
        ),
    ]
