version: '3.8'

services:
  web:
    build: ./ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ecommerce/:/Users/kkk_kkkkkkk/Documents/hs/ecommerce
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  pgdb:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_volume: