version: '3.8'

services:
  django:
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    restart: always
    command: >
      sh -c "gunicorn --bind 194.58.111.67:8000 app.wsgi"
    volumes:
      - ./ecommerce:/ecommerce
      - static_data:/ecommerce/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgres/data/
    environment:
      - POSTGRES_DATABASE=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:1.22.0-alpine
    depends_on:
      - django
    ports:
      - "8080:8080"
    volumes:
      - static_data:/home/site/server/hs
      - ./nginx-conf.d:/etc/nginx/conf.d

  redis:
    image: redis:alpine
    ports:
      - 3306:3306
    entrypoint: redis-server --appendonly yes

  celery:
    restart: always
    build:
      context: .
    command: celery -A ecommerce_celery worker -l info
    # volumes:
    #   - ./app:/app
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
      - django

volumes:
  postgres_volume:
  static_data: