version: '3.8'

services:
  pgdb:
    container_name: ecommerce_eve
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=ecomemrce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres