version: '3.8'

services:
  web:
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 194.58.111.67:8000"
    # volumes:
    #   - ./ecommerce/:/Users/kkk_kkkkkkk/Documents/hs/ecommerce
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/mysql/data/
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DATABASE=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    ports:
      - 3306:3306
    entrypoint: redis-server --appendonly yes

  celery:
    restart: always
    build:
      context: .
    command: celery -A ecommerce_celery worker -l info
    # volumes:
    #   - ./app:/app
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
      - web

volumes:
  postgres_volume: