version: '3.8'

services:
  django:
    image: registry.gitlab.com/eveshop21/backend:latest
    restart: always
    volumes:
      - ./static_data:/app/static
      - ./media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgres/data/
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    ports:
      - 3306:3306
    entrypoint: redis-server --appendonly yes

  celery:
    restart: always
    image: registry.gitlab.com/eveshop21/backend:latest
    command: celery -A ecommerce_celery worker -l info
    depends_on:
      - pgdb
      - redis
      - django
  front:
    restart: always
    image: registry.gitlab.com/eveshop21/frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./static_data:/app/static
      - ./media_data:/app/media
      - /etc/ssl:/etc/ssl/
    depends_on:
      - pgdb
      - redis
      - django
      - celery

volumes:
  postgres_volume:
  static_data:
