# Generated by Django 4.1.2 on 2023-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='azaza', verbose_name='Адрес пункта выдачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.CharField(default='azazaza', max_length=30, verbose_name='Стоимость доставки'),
            preserve_default=False,
        ),
    ]
