# Generated by Django 4.1.2 on 2022-12-08 10:44

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, help_text='Формат: обязательный', null=True, to='core.category', verbose_name='Выбрать категорию к которой привязан данный тип товара'),
        ),
    ]
