# Generated by Django 4.1.2 on 2022-12-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.productinventory'),
        ),
    ]
