# Generated by Django 4.1.2 on 2023-01-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_variation_product_productinventory_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='variation',
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='core.productinventory'),
            preserve_default=False,
        ),
    ]
