# Generated by Django 4.1.2 on 2023-03-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(help_text='Создается автоматически', max_length=100, verbose_name='ID оплаченного платежа за заказ')),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, help_text='Создается автоматически', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='orders.order', verbose_name='Оплаченный заказ')),
            ],
        ),
    ]
