# Generated by Django 4.1.2 on 2023-01-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email_alter_order_name_alter_order_phone_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Создается автоматически', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='orders.order', verbose_name='Оплаченный заказ'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='payment_id',
            field=models.CharField(help_text='Создается автоматически', max_length=100, verbose_name='ID оплаченного платежа за заказ'),
        ),
    ]
