# Generated by Django 4.1.2 on 2023-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Формат: обязательный', max_length=255, verbose_name='Почта клиента, оформившего и купившего товары (заказ)')),
                ('message', models.TextField(help_text='Формат: обязательный', verbose_name='Текст сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSendAutomaticly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Формат: обязательный', max_length=254, verbose_name='Почта для отправки смс покупателю')),
                ('subject', models.CharField(help_text='Формат: обязательный', max_length=255, verbose_name='Шапка смс для отправки почты покупателю')),
                ('text', models.TextField(help_text='Формат: обязательный', verbose_name='Текст смс для отправки почты покупателю')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Нажать, если нужно удалить шаблон')),
            ],
        ),
    ]
