# Generated by Django 4.1.2 on 2023-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_emailsendautomaticly_template_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailentry',
            options={'verbose_name': 'Отправленный имейл при оформлении заказа', 'verbose_name_plural': 'Отправленные имейлы при оформлении заказа'},
        ),
        migrations.AlterModelOptions(
            name='emailsendautomaticly',
            options={'verbose_name': 'Отправить имейл рассылку', 'verbose_name_plural': 'Отправить имейл рассылку'},
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='template_name',
            field=models.TextField(blank=True, help_text='Название шаблона', null=True, verbose_name='Имя шаблона письма'),
        ),
    ]
