# Generated by Django 4.1.2 on 2023-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_emailentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendautomaticly',
            name='template_name',
            field=models.TextField(blank=True, help_text='Название шаблона', null=True, verbose_name='Имя шаблона письма'),
        ),
    ]
