# Generated by Django 4.1.2 on 2023-04-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitems_options_and_more'),
        ('mailing', '0010_emailentry_is_deleted_emailsendtemplate_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendautomaticly',
            name='email_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_emails', to='orders.order'),
        ),
    ]
