# Generated by Django 4.1.2 on 2023-07-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_is_paid'),
        ('mailing', '0013_remove_emailsendautomaticly_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendautomaticly',
            name='email_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_emails', to='orders.order', verbose_name='Номер заказа'),
        ),
    ]
