# Generated by Django 4.1.2 on 2023-09-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_is_paid'),
        ('mailing', '0014_alter_emailsendautomaticly_email_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='orders.order', verbose_name='Текущий заказ клиента'),
        ),
    ]
