# Generated by Django 4.1.2 on 2023-03-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdata',
            options={'verbose_name': 'ID заказа', 'verbose_name_plural': 'ID заказов'},
        ),
    ]
