# Generated by Django 4.1.2 on 2023-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Галочка стоит, если заказ оплачен'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Выбрать, если нужно удалить'),
        ),
    ]
