# Generated by Django 4.1.2 on 2023-09-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_is_paid'),
        ('payment', '0003_paymentdata_is_paid_alter_paymentdata_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Создается автоматически', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='orders.order', verbose_name='Заказ'),
        ),
    ]
