# Generated by Django 4.1.2 on 2022-12-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_api', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Имя товара')),
                ('email', models.EmailField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Имя товара')),
                ('phone', models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Имя товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Определяется автоматически, возможно редактирование', verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, help_text='Формат: обязательный', verbose_name='Выбрать, если товар используется в каталоге')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если товар должен быть удалена')),
                ('coupon_discount', models.PositiveIntegerField(help_text='% взята из скидки Купона', verbose_name='Скидка по купону в %')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Сформирована автоматически', max_digits=7, verbose_name='Общая стоимость заказа')),
                ('is_paid', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, help_text='Связан с категорий Купон', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coupon_api.coupon', verbose_name='Использованный при оплате купон')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('qunatity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Определяется автоматически, возможно редактирование', verbose_name='Дата создания')),
                ('id_deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_order', to='core.variation')),
            ],
        ),
    ]
