# Generated by Django 4.1.2 on 2023-01-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_productinventory_media_media_product'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Почта покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Номер покупателя'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='id_deleted',
            field=models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если вариация товара в заказе должна быть удалена'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(help_text='Сформирован автоматически', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order', verbose_name='Текущий заказ'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Сформирована автоматически', max_digits=7, verbose_name='Cтоимость товара в текущем заказе'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product_variation',
            field=models.ForeignKey(help_text='Сформированы автоматически', on_delete=django.db.models.deletion.PROTECT, related_name='current_order', to='core.variation', verbose_name='Вариации товара в текущем заказе'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='qunatity',
            field=models.PositiveIntegerField(default=1, help_text='Сформировано автоматически', verbose_name='Общее количество товара в текущем заказе'),
        ),
    ]
