# Generated by Django 4.1.2 on 2023-03-04 16:10

import core.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White')], max_length=25, null=True, verbose_name='Цвет товара')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если цвет товара должен быть удален')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, unique=True, verbose_name='Имя категории товара')),
                ('slug', models.SlugField(help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, unique=True, verbose_name='Наименование категории товара в URL')),
                ('description', models.TextField(blank=True, help_text='Формат: обязательный', null=True, verbose_name='Описание типа товара')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если тип товара должен быть удалена')),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Имя товара')),
                ('slug', models.CharField(help_text='Формат: обязательный, максимальная длина - 255', max_length=255, verbose_name='Путь до товара')),
                ('store_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'Цена товара должна быть между 0 и 99999.99.'}}, help_text='Формат: число, максимальное значение - 99999.99', max_digits=7, verbose_name='Базовая стоимость товара')),
                ('retail_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'Цена товара должна быть между 0 и 99999.99.'}}, help_text='Формат: число, максимальное значение - 99999.99', max_digits=7, verbose_name='Цена продажи')),
                ('description', models.TextField(blank=True, help_text='Формат: обязательный', null=True, verbose_name='Описание товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Определяется автоматически, возможно редактирование', verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если товар должен быть удалена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='core.product')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLARGE')], max_length=20, null=True, verbose_name='Размер товара')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если размер товара должен быть удален')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры товаров',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, help_text='Формат: обязательный', verbose_name='Количество комбинации')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если вариация товара должна быть удалена')),
                ('color', models.ManyToManyField(help_text='Формат: обязательный', to='core.color', verbose_name='Цвет')),
                ('product', models.ForeignKey(help_text='Формат: обязательный', on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='core.productinventory', verbose_name='Выбрать наименование товара')),
                ('size', models.ManyToManyField(help_text='Формат: обязательный', to='core.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Вариации товаров',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=core.models._set_directory_to_ipload_images)),
                ('is_default', models.BooleanField(default=False, help_text='Формат: необязательный', verbose_name='Выбрать, если фото товара главное ')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если фото товара должно быть удалено')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.productinventory')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, unique=True, verbose_name='Имя категории товара')),
                ('slug', models.SlugField(blank=True, help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, null=True, unique=True, verbose_name='Путь до товаров этой категории')),
                ('is_active', models.BooleanField(default=True, help_text='Формат: обязательный', verbose_name='Выбрать, если категория используется в каталоге')),
                ('is_deleted', models.BooleanField(default=False, help_text='Формат: обязательный', verbose_name='Выбрать, если категория должна быть удалена')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Формат: необязательный', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.category', verbose_name='Дочерняя категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
