# Generated by Django 4.1.2 on 2023-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='count',
            field=models.PositiveIntegerField(help_text='Формат: обязательный', verbose_name='Количество комбинации'),
        ),
    ]
